---
name: CI - Build
on:
  workflow_call:
    outputs:
      jar_path:
        description: 'Path to the built JAR file(s)'
        value: ${{ jobs.build.outputs.jar_path }}

jobs:
  build:
    runs-on: self-hosted
    outputs:
      jar_path: '/build/libs/flash-cards-app-0.0.1-SNAPSHOT.jar'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: 23
          distribution: corretto
          cache: gradle
          cache-dependency-path: |
            *.gradle*
            libs.versions.toml            
            flash-cards-api/*.gradle*

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build
...
